### ISSUE TITLE
make --endpoint-url configurable by environment, or move it before the subcommand

### ISSUE THREAD

**Issue by smousa** [ktrueda/parquet-tools#52]
Hello!

I have tried quite a few parquet cli's out there, and I think this one is the best!

Here is my use case:
 I am running this tool in a local environment in docker compose against a local s3 emulator/server.  However, because the `--endpoint-url` occurs after the subcommands and not the main command, it's makes my requests a little more verbose to work with.  Here is what I mean...

This is my docker-compose:
```yaml
services:
    s3:
    image: scireum/s3-ninja
    pull_policy: always
    ports:
      - 9000:9000
    labels:
      - traefik.enable=true
      - traefik.http.routers.s3.rule=Host(`s3`) && PathPrefix(`/`)
      - traefik.http.services.s3.loadbalancer.server.port=9000

  parquet-tools:
    profiles:
      - script
    build:
      dockerfile_inline: | 
        ARG PYTHON_TOOLS_VERSION=0.2.15
        FROM apache/arrow-dev:amd64-conda-python-3.10
        RUN python -m ensurepip --upgrade
        RUN pip install parquet-tools==0.2.15
    environment:
      AWS_ACCESS_KEY_ID:  ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint:
      - parquet-tools
    depends_on:
      - s3

  aws-cli:
    profiles:
      - script
    image: public.ecr.aws/aws-cli/aws-cli
    pull_policy: always
    environment:
      AWS_ACCESS_KEY_ID:  ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint:
      - aws
      - --endpoint-url
      - http://s3:9000
    depends_on:
      - s3

volumes:
  s3:

```

Now in comparing the aws-cli service and the parquet-tools service, you notice that I can add the `--endpoint-url` to the entrypoint such that when I run it from the cli it looks like this:

```bash
$ docker compose run --rm aws-cli s3 ls s3://BUCKET/...
```

When using the parquet-tools binary, I have to do something like:
```bash
$ docker compose run --rm parquet-tools show --endpoint-url http://s3:9000 s3://BUCKET/...
```

I would love if I could call the command like this against my local s3 (either by moving the flag or having the flag supported by env var):
```bash
$ docker compose run --rm parquet-tools show s3://BUCKET/...
```

Thanks!
